# Generated by Django 4.1.1 on 2022-10-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.CharField(help_text='One of Email or Msisdn', max_length=255)),
                ('otp', models.CharField(db_index=True, max_length=10)),
                ('secret', models.CharField(db_index=True, max_length=255)),
                ('valid_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('valid_until_timestamp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
