# Generated by Django 4.1.3 on 2022-12-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
