# Generated by Django 4.1.2 on 2022-10-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UOTP',
        ),
    ]
