# Generated by Django 3.2.15 on 2022-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220929_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='relation',
            field=models.CharField(choices=[('father', 'Male'), ('mother', 'Female'), ('spouse', 'Spouse'), ('son', 'Son'), ('daughter', 'Daughter'), ('family', 'Family')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=255),
        ),
    ]
