# Generated by Django 4.1.1 on 2022-11-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_otp_profile_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
