# Generated by Django 4.1.1 on 2022-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='uotp',
            name='purpose',
            field=models.CharField(choices=[('signin', 'Sign In')], default='signin', max_length=15),
            preserve_default=False,
        ),
    ]
