# Generated by Django 4.1.1 on 2022-10-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uotp',
            name='purpose',
            field=models.CharField(choices=[('signin', 'Sign In')], default='signin', max_length=15),
        ),
    ]
