# Generated by Django 4.1.3 on 2022-12-05 23:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Home Collection',
                'verbose_name_plural': 'Home Collection',
                'ordering': ('full_name',),
            },
        ),
    ]
