# Generated by Django 4.1.1 on 2022-11-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='signature_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
