# Generated by Django 4.1.1 on 2022-11-13 06:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_order_id_remove_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='report',
            field=models.FileField(blank=True, upload_to=shop.models.pdf_upload_path),
        ),
    ]
