# Generated by Django 4.1.1 on 2022-10-21 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cutoff',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='report',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='shop.category'),
        ),
    ]
