# Generated by Django 4.1.1 on 2022-10-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_tags_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='speciment',
        ),
    ]
