# Generated by Django 4.1.1 on 2022-10-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_description_product_speciment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cutoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='speciment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
