# Generated by Django 4.1.1 on 2022-10-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_method_product_quantitytemperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cutoff',
            new_name='cutofftime',
        ),
        migrations.AddField(
            model_name='product',
            name='samplecutoff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
